
ALTER TABLE usuarios
ADD COLUMN senha_hash VARCHAR(255) NULL,
ADD COLUMN reset_token VARCHAR(255) NULL;

CREATE TABLE logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_email VARCHAR(100),
  acao TEXT,
  momento DATETIME DEFAULT CURRENT_TIMESTAMP
);
